# Generated by Django 4.0.4 on 2022-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='done',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('content', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('1', 'High Priority'), ('2', 'Middle Priority'), ('3', 'Low Priority')], default='Middle Priority', max_length=50)),
                ('tag', models.CharField(default='independent', max_length=20)),
            ],
        ),
    ]
