# Generated by Django 4.0.4 on 2022-05-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('High Priority', '1'), ('Middle Priority', '2'), ('Low Priority', '3')], default='Middle Priority', max_length=50),
        ),
    ]
