# Generated by Django 4.0.4 on 2022-05-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('High Priority', 'High Priority'), ('Middle Priority', 'High Priority'), ('Low Priority', 'High Priority')], default='Middle Priority', max_length=50),
        ),
    ]
