# Generated by Django 4.0.4 on 2022-05-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_done_priority_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='done',
            name='priority',
            field=models.CharField(choices=[('High Priority', 'High Priority'), ('Middle Priority', 'Middle Priority'), ('Low Priority', 'Low Priority')], default='Middle Priority', max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('High Priority', 'High Priority'), ('Middle Priority', 'Middle Priority'), ('Low Priority', 'Low Priority')], default='Middle Priority', max_length=50),
        ),
    ]
