# Generated by Django 4.0.4 on 2022-05-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_done_priority_alter_todo_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='done',
        ),
        migrations.AddField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
