# Generated by Django 4.0.4 on 2022-05-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.CharField(default='Daily', max_length=20),
        ),
    ]
