# Generated by Django 4.0.4 on 2022-05-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_todo_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('High Priority', 'High Priority'), ('Middle Priority', 'Middle Priority'), ('Low Priority', 'Low Priority')], max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
